//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : pd
//  @ File Name : searchController.java
//  @ Date : 2019/4/19
//  @ Author : 
//
//



package com.pd.controller;


public class searchController {
	public String search(String key, String username) {
		return null;
	}
}
