//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : pd
//  @ File Name : SearchServiceImpl.java
//  @ Date : 2019/4/19
//  @ Author : 
//
//



package com.pd.service;


public class SearchServiceImpl {
}
