//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : pd
//  @ File Name : Item.java
//  @ Date : 2019/4/19
//  @ Author : 
//
//



package com.pd.pojo;


public class Item {
	public String title;
	public Long price;
	public String getTitle() {
		return title;
	}
	
	public void setTitle(String title) {
	
	}
}
